version: '0.0'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
